let a=10;
let b=5;
console.log("Arithmetic Operators:");
console.log("Addition:",a+b);
console.log("Subtraction:",a-b);
console.log("Multiplication:",a*b);
console.log("Division:",a/b);
console.log("Modulus:",a%b);
console.log("Exponentiation:",a**b);
let x=10;
let y=5;
console.log("\nComparison Operators:\n");
console.log("Equal:",a==b);
console.log("Not Equal:",a!=b);
let q=2;
let r='2';
console.log("Equal with Type Coercion:",q==r);
console.log("Strict Equal:",a===b);
console.log("Strict Equal:",a!==b);
console.log("\nLogical Operators:");
console.log("AND:",a>5 && b<10);
console.log("OR:",a>5 || b<10);
console.log("NOT:",!(a>5));
console.log("\nBitwise Operators:");
console.log("Bitwise AND",a&b);
console.log("Bitwise OR",a|b);
console.log("Bitwise XOR",a^b);
console.log("Left Shift:",a<<1);
console.log("Right Shift:",a>>1);
let age=18;
let canVote=(age>=18)?"You Can vote.":"You cannot vote.";
console.log("\nTernary Operator:");
console.log("Result:",canVote);
console.log("\nType of Operator:");
console.log("Type of a:",typeof a);
console.log("Type of b",typeof b);
console.log("Type of x:",typeof x);
console.log("TYpe of y:",typeof y);
console.log("Type of canVote",typeof canVote);

